### ISSUE TITLE
Recognize more spellings of ꝡ in queries

### ISSUE THREAD

**Issue by lynn** [toaq/toadua#28]
Currently, only the queries `vyao` and `ꝡao` bring up the definition for **ꝡao**.

Searching for `vao` or `wao` or `yao` should probably also work.

**Comment by uakci** [comment]
I have a hunch that because of the complicated mapping between Toaq and English, we're gonna have to do two searches for each query, one for the unconverted input ("English") and one for the converted input ("Toaq"). This would free us to convert all of `vyao`, `vao`, `yao`, `wao` to `ꝡao` without impacting the accuracy of English full-text search.

**Comment by uakci** [comment]
Closed in #37.
