### ISSUE TITLE
Don't import `countries` -zu words

### ISSUE THREAD

**Issue by lynn** [toaq/toadua#40]
I think we are better off having human-curated definitions like

> **Faraqsezu** = ▯ is the French language.

than automatic definitions like

> **Faraqsezu** = ▯ is (one of) the language(s) spoken in France – French Republic.
>
> **Monakozu** = ▯ is (one of) the language(s) spoken in Monaco – Principality of Monaco.
>
> **Kotıbuarezu** = ▯ is (one of) the language(s) spoken in Côte d'Ivoire → Ivory Coast.

which are clunkily phrased and raise all kinds of questions.

(I think the automatic definitions for **Monako** and **Monakogua** are less problematic.)

**Comment by uakci** [comment]
So I’m looking at this trying to think how to make this happen since the synchronization logic wipes all entries that aren’t present upstream. So this would mean a huge exodus of **–zu** words – unless that’s exactly what you want?

Another option could be to “physically” remove (blank out) the **–zu** entries that you don’t think hold up to scrutiny.

**Comment by uakci** [comment]
So I’m looking at this trying to think how to make this happen since the synchronization logic wipes all entries that aren’t present upstream. So this would mean a huge exodus of **–zu** words – unless that’s exactly what you want?

Another option could be to “physically” remove (blank out) the **–zu** entries that you don’t think hold up to scrutiny.
